// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlEzc7Pu03M6vcRZbxr7pRzYV0RP5ESek',
    appId: '1:784241754794:web:c946bfb8df7729662706d3',
    messagingSenderId: '784241754794',
    projectId: 'mobile-programing-660c9',
    authDomain: 'mobile-programing-660c9.firebaseapp.com',
    storageBucket: 'mobile-programing-660c9.firebasestorage.app',
    measurementId: 'G-HLKSDS3V1Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2PMFyIfGkFg9hwAymtTOTBfC4M4ylXZk',
    appId: '1:784241754794:android:5304259b10f6ba4b2706d3',
    messagingSenderId: '784241754794',
    projectId: 'mobile-programing-660c9',
    storageBucket: 'mobile-programing-660c9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIrRZ-2rl-_s3T3IyyPPPJT4XTV4Q-up0',
    appId: '1:784241754794:ios:f66787b8290013972706d3',
    messagingSenderId: '784241754794',
    projectId: 'mobile-programing-660c9',
    storageBucket: 'mobile-programing-660c9.firebasestorage.app',
    iosBundleId: 'com.example.flutterP10',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIrRZ-2rl-_s3T3IyyPPPJT4XTV4Q-up0',
    appId: '1:784241754794:ios:f66787b8290013972706d3',
    messagingSenderId: '784241754794',
    projectId: 'mobile-programing-660c9',
    storageBucket: 'mobile-programing-660c9.firebasestorage.app',
    iosBundleId: 'com.example.flutterP10',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBlEzc7Pu03M6vcRZbxr7pRzYV0RP5ESek',
    appId: '1:784241754794:web:e073b381f68615cf2706d3',
    messagingSenderId: '784241754794',
    projectId: 'mobile-programing-660c9',
    authDomain: 'mobile-programing-660c9.firebaseapp.com',
    storageBucket: 'mobile-programing-660c9.firebasestorage.app',
    measurementId: 'G-VB651V23L6',
  );
}